# MSWEP: Weighted Precipitation Time Series

In [1]:
import os
import sys
import glob
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
import rioxarray
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor
from exactextract import exact_extract
from shapely.geometry import box

In [ ]:
# Suppress noisy xattr errors from MSWEP files
sys.stderr = open(os.devnull, "w")

getfattr: /inputs/MSWEP_V280/Past/Daily/1989001.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989001.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989003.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989002.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989004.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989005.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989006.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989007.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989008.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989009.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989010.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989011.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989012.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989013.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989014.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989015.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989016.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989017.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989018.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989020.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989019.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989021.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989022.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989023.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989024.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989025.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989026.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989027.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989028.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989029.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989030.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989031.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989032.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989033.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989037.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989036.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989035.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989038.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989039.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989040.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989042.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989041.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989043.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989044.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989045.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989046.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989047.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989048.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989049.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989050.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989051.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989052.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989053.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989054.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989055.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989056.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989058.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989057.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989059.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989061.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989060.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989062.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989063.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989064.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989065.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989066.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989067.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989068.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989069.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989070.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989071.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989072.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989073.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989034.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989075.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989074.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989076.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989077.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989078.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989080.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989079.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989081.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989082.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989083.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989084.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989086.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989085.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989087.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989088.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989090.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989089.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989091.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989092.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989093.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989094.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989096.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989095.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989097.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989098.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989099.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989100.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989101.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989102.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989103.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989104.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989105.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989106.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989107.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989108.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989109.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989110.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989111.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989112.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989113.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989114.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989115.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989116.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989117.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989118.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989119.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989120.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989121.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989122.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989123.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989124.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989125.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989126.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989128.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989129.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989127.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989130.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989131.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989132.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989133.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989134.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989135.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989136.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989137.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989138.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989139.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989141.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989140.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989142.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989143.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989144.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989146.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989145.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989147.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989148.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989149.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989150.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989151.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989154.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989152.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989153.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989155.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989157.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989156.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989158.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989160.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989159.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989161.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989162.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989163.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989164.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989165.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989166.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989167.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989168.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989169.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989170.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989171.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989172.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989173.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989174.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989175.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989178.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989176.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989177.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989179.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989180.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989181.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989182.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989183.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989184.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989185.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989186.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989187.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989188.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989190.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989189.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989192.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989191.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989194.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989193.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989195.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989197.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989198.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989196.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989199.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989202.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989201.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989200.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989203.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989204.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989206.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989205.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989207.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989208.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989209.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989210.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989211.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989212.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989213.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989214.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989215.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989216.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989218.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989217.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989219.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989220.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989221.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989222.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989223.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989226.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989225.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989224.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989230.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989227.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989229.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989228.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989231.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989232.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989233.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989234.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989235.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989236.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989237.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989238.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989239.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989240.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989241.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989242.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989243.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989244.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989245.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989246.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989248.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989249.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989250.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989251.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989252.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989253.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989254.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989255.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989256.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989257.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989247.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989258.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989259.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989261.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989260.nc: Operation not supported
getfattr: /inputs/MSWEP_V280/Past/Daily/1989262.nc: Operation not supported

In [ ]:
# ── Inputs ──────────────────────────────────────────────────────────────────
shapefile_path   = Path("./caravan_shapefiles/camels/camels_basin_shapes.shp")
basins_txt_file  = Path("./basins_subset_test.txt")
mswep_dir        = Path("/inputs/MSWEP_V280/Past/Daily")

# Year range to process (adjust as needed)
YEAR_START, YEAR_END = 1989, 2019 #1989, 2008 

# ── Outputs ─────────────────────────────────────────────────────────────────
output_dir = Path("./mswep_precip_timeseries")
output_dir.mkdir(exist_ok=True)

In [4]:
gdf = gpd.read_file(shapefile_path)

with open(basins_txt_file) as f:
    selected_basins = [line.strip() for line in f.readlines()]

basins_gdf = gdf[gdf["gauge_id"].isin(selected_basins)].to_crs("EPSG:4326")
print(f"Loaded {len(basins_gdf)} basins")
basins_gdf.head()

Loaded 127 basins

           gauge_id                                           geometry
31  camels_01411300  POLYGON ((-74.82836 39.38169, -74.83051 39.379...
42  camels_01466500  POLYGON ((-74.49563 39.89106, -74.4926 39.8866...
46  camels_01487000  MULTIPOLYGON (((-75.51965 38.87137, -75.51541 ...
80  camels_01638480  POLYGON ((-77.59039 39.2801, -77.58784 39.2789...
82  camels_01644000  POLYGON ((-77.79457 39.16487, -77.78732 39.159...

In [5]:
# extracted_mswep = {
#     f.replace("_precip.csv", "")
#     for f in os.listdir("./precip_timeseries_mswep_weighted")
#     if f.endswith("_precip.csv")
# }

# basins_gdf_filtered = basins_gdf[~basins_gdf["gauge_id"].isin(extracted_mswep)]

# print(f"Original: {len(basins_gdf)}, Extracted: {len(extracted_mswep)}, Remaining: {len(basins_gdf_filtered)}")

In [6]:
# basins_gdf = basins_gdf_filtered

In [7]:
gauges = list(basins_gdf["gauge_id"])

gdf_all = gpd.GeoDataFrame(
    {"gauge_id": gauges},
    geometry=list(basins_gdf.geometry),
    crs="EPSG:4326",
)
gdf_all.head()

          gauge_id                                           geometry
0  camels_01411300  POLYGON ((-74.82836 39.38169, -74.83051 39.379...
1  camels_01466500  POLYGON ((-74.49563 39.89106, -74.4926 39.8866...
2  camels_01487000  MULTIPOLYGON (((-75.51965 38.87137, -75.51541 ...
3  camels_01638480  POLYGON ((-77.59039 39.2801, -77.58784 39.2789...
4  camels_01644000  POLYGON ((-77.79457 39.16487, -77.78732 39.159...

In [8]:
all_files = sorted(mswep_dir.glob("*.nc"))

# Filter by year encoded in the filename (first 4 characters)
files = [
    f for f in all_files
    if YEAR_START <= int(f.stem[:4]) <= YEAR_END
]

print(f"Total MSWEP files to process: {len(files)}")
files[:3]

Total MSWEP files to process: 11322

[PosixPath('/inputs/MSWEP_V280/Past/Daily/1989001.nc'),
 PosixPath('/inputs/MSWEP_V280/Past/Daily/1989002.nc'),
 PosixPath('/inputs/MSWEP_V280/Past/Daily/1989003.nc')]

In [10]:
def process_file_weighted(file_path, gdf_all, gauges):
    stem = file_path.stem
    year = int(stem[:4])
    doy  = int(stem[4:])
    date = pd.Timestamp(year=year, month=1, day=1) + pd.Timedelta(days=doy - 1)

    ds = xr.open_dataset(file_path)
    da = ds["precipitation"].squeeze()

    rename_map = {}
    if "lon" in da.dims: rename_map["lon"] = "x"
    if "lat" in da.dims: rename_map["lat"] = "y"
    da = da.rename(rename_map)
    da = da.rio.write_crs("EPSG:4326")

    result = exact_extract(da, gdf_all, ["mean"], output="pandas")
    result["mean"] = result["mean"].where(
        (result["mean"] != -9999) & (result["mean"] >= 0), other=np.nan
    )
    ds.close()
    return date, dict(zip(gauges, result["mean"].values))

In [11]:
# Run ONE file synchronously to confirm the function itself works
date, values = process_file_weighted(files[0], gdf_all, gauges)
print(date, list(values.items())[:3])

1989-01-01 00:00:00 [('camels_01411300', np.float64(3.2148521470474924)), ('camels_01466500', np.float64(2.1081729654427166)), ('camels_01487000', np.float64(6.2382447854460565))]

In [13]:
all_results = []
with ProcessPoolExecutor() as executor:
    futures = [executor.submit(process_file_weighted, f, gdf_all, gauges) for f in files]
    for i, future in enumerate(futures, 1):
        date, values = future.result()
        all_results.append((date, values))
        print(f"{date.date()} processed ({i}/{len(files)})")

1989-01-01 processed (1/11322)
1989-01-02 processed (2/11322)
1989-01-03 processed (3/11322)
1989-01-04 processed (4/11322)
1989-01-05 processed (5/11322)
1989-01-06 processed (6/11322)
1989-01-07 processed (7/11322)
1989-01-08 processed (8/11322)
1989-01-09 processed (9/11322)
1989-01-10 processed (10/11322)
1989-01-11 processed (11/11322)
1989-01-12 processed (12/11322)
1989-01-13 processed (13/11322)
1989-01-14 processed (14/11322)
1989-01-15 processed (15/11322)
1989-01-16 processed (16/11322)
1989-01-17 processed (17/11322)
1989-01-18 processed (18/11322)
1989-01-19 processed (19/11322)
1989-01-20 processed (20/11322)
1989-01-21 processed (21/11322)
1989-01-22 processed (22/11322)
1989-01-23 processed (23/11322)
1989-01-24 processed (24/11322)
1989-01-25 processed (25/11322)
1989-01-26 processed (26/11322)
1989-01-27 processed (27/11322)
1989-01-28 processed (28/11322)
1989-01-29 processed (29/11322)
1989-01-30 processed (30/11322)
1989-01-31 processed (31/11322)
1989-02-01 processed (32/11322)
1989-02-02 processed (33/11322)
1989-02-03 processed (34/11322)
1989-02-04 processed (35/11322)
1989-02-05 processed (36/11322)
1989-02-06 processed (37/11322)
1989-02-07 processed (38/11322)
1989-02-08 processed (39/11322)
1989-02-09 processed (40/11322)
1989-02-10 processed (41/11322)
1989-02-11 processed (42/11322)
1989-02-12 processed (43/11322)
1989-02-13 processed (44/11322)
1989-02-14 processed (45/11322)
1989-02-15 processed (46/11322)
1989-02-16 processed (47/11322)
1989-02-17 processed (48/11322)
1989-02-18 processed (49/11322)
1989-02-19 processed (50/11322)
1989-02-20 processed (51/11322)
1989-02-21 processed (52/11322)
1989-02-22 processed (53/11322)
1989-02-23 processed (54/11322)
1989-02-24 processed (55/11322)
1989-02-25 processed (56/11322)
1989-02-26 processed (57/11322)
1989-02-27 processed (58/11322)
1989-02-28 processed (59/11322)
1989-03-01 processed (60/11322)
1989-03-02 processed (61/11322)
1989-03-03 processed (62/11322)
1989-03-04 processed (63/11322)
1989-03-05 processed (64/11322)
1989-03-06 processed (65/11322)
1989-03-07 processed (66/11322)
1989-03-08 processed (67/11322)
1989-03-09 processed (68/11322)
1989-03-10 processed (69/11322)
1989-03-11 processed (70/11322)
1989-03-12 processed (71/11322)
1989-03-13 processed (72/11322)
1989-03-14 processed (73/11322)
1989-03-15 processed (74/11322)
1989-03-16 processed (75/11322)
1989-03-17 processed (76/11322)
1989-03-18 processed (77/11322)
1989-03-19 processed (78/11322)
1989-03-20 processed (79/11322)
1989-03-21 processed (80/11322)
1989-03-22 processed (81/11322)
1989-03-23 processed (82/11322)
1989-03-24 processed (83/11322)
1989-03-25 processed (84/11322)
1989-03-26 processed (85/11322)
1989-03-27 processed (86/11322)
1989-03-28 processed (87/11322)
1989-03-29 processed (88/11322)
1989-03-30 processed (89/11322)
1989-03-31 processed (90/11322)
1989-04-01 processed (91/11322)
1989-04-02 processed (92/11322)
1989-04-03 processed (93/11322)
1989-04-04 processed (94/11322)
1989-04-05 processed (95/11322)
1989-04-06 processed (96/11322)
1989-04-07 processed (97/11322)
1989-04-08 processed (98/11322)
1989-04-09 processed (99/11322)
1989-04-10 processed (100/11322)
1989-04-11 processed (101/11322)
1989-04-12 processed (102/11322)
1989-04-13 processed (103/11322)
1989-04-14 processed (104/11322)
1989-04-15 processed (105/11322)
1989-04-16 processed (106/11322)
1989-04-17 processed (107/11322)
1989-04-18 processed (108/11322)
1989-04-19 processed (109/11322)
1989-04-20 processed (110/11322)
1989-04-21 processed (111/11322)
1989-04-22 processed (112/11322)
1989-04-23 processed (113/11322)
1989-04-24 processed (114/11322)
1989-04-25 processed (115/11322)
1989-04-26 processed (116/11322)
1989-04-27 processed (117/11322)
1989-04-28 processed (118/11322)
1989-04-29 processed (119/11322)
1989-04-30 processed (120/11322)
1989-05-01 processed (121/11322)
1989-05-02 processed (122/11322)
1989-05-03 processed (123/11322)
1989-05-04 processed (124/11322)
1989-05-05 processed (125/11322)
1989-05-06 processed (126/11322)
1989-05-07 processed (127/11322)
1989-05-08 processed (128/11322)
1989-05-09 processed (129/11322)
1989-05-10 processed (130/11322)
1989-05-11 processed (131/11322)
1989-05-12 processed (132/11322)
1989-05-13 processed (133/11322)
1989-05-14 processed (134/11322)
1989-05-15 processed (135/11322)
1989-05-16 processed (136/11322)
1989-05-17 processed (137/11322)
1989-05-18 processed (138/11322)
1989-05-19 processed (139/11322)
1989-05-20 processed (140/11322)
1989-05-21 processed (141/11322)
1989-05-22 processed (142/11322)
1989-05-23 processed (143/11322)
1989-05-24 processed (144/11322)
1989-05-25 processed (145/11322)
1989-05-26 processed (146/11322)
1989-05-27 processed (147/11322)
1989-05-28 processed (148/11322)
1989-05-29 processed (149/11322)
1989-05-30 processed (150/11322)
1989-05-31 processed (151/11322)
1989-06-01 processed (152/11322)
1989-06-02 processed (153/11322)
1989-06-03 processed (154/11322)
1989-06-04 processed (155/11322)
1989-06-05 processed (156/11322)
1989-06-06 processed (157/11322)
1989-06-07 processed (158/11322)
1989-06-08 processed (159/11322)
1989-06-09 processed (160/11322)
1989-06-10 processed (161/11322)
1989-06-11 processed (162/11322)
1989-06-12 processed (163/11322)
1989-06-13 processed (164/11322)
1989-06-14 processed (165/11322)
1989-06-15 processed (166/11322)
1989-06-16 processed (167/11322)
1989-06-17 processed (168/11322)
1989-06-18 processed (169/11322)
1989-06-19 processed (170/11322)
1989-06-20 processed (171/11322)
1989-06-21 processed (172/11322)
1989-06-22 processed (173/11322)
1989-06-23 processed (174/11322)
1989-06-24 processed (175/11322)
1989-06-25 processed (176/11322)
1989-06-26 processed (177/11322)
1989-06-27 processed (178/11322)
1989-06-28 processed (179/11322)
1989-06-29 processed (180/11322)
1989-06-30 processed (181/11322)
1989-07-01 processed (182/11322)
1989-07-02 processed (183/11322)
1989-07-03 processed (184/11322)
1989-07-04 processed (185/11322)
1989-07-05 processed (186/11322)
1989-07-06 processed (187/11322)
1989-07-07 processed (188/11322)
1989-07-08 processed (189/11322)
1989-07-09 processed (190/11322)
1989-07-10 processed (191/11322)
1989-07-11 processed (192/11322)
1989-07-12 processed (193/11322)
1989-07-13 processed (194/11322)
1989-07-14 processed (195/11322)
1989-07-15 processed (196/11322)
1989-07-16 processed (197/11322)
1989-07-17 processed (198/11322)
1989-07-18 processed (199/11322)
1989-07-19 processed (200/11322)
1989-07-20 processed (201/11322)
1989-07-21 processed (202/11322)
1989-07-22 processed (203/11322)
1989-07-23 processed (204/11322)
1989-07-24 processed (205/11322)
1989-07-25 processed (206/11322)
1989-07-26 processed (207/11322)
1989-07-27 processed (208/11322)
1989-07-28 processed (209/11322)
1989-07-29 processed (210/11322)
1989-07-30 processed (211/11322)
1989-07-31 processed (212/11322)
1989-08-01 processed (213/11322)
1989-08-02 processed (214/11322)
1989-08-03 processed (215/11322)
1989-08-04 processed (216/11322)
1989-08-05 processed (217/11322)
1989-08-06 processed (218/11322)
1989-08-07 processed (219/11322)
1989-08-08 processed (220/11322)
1989-08-09 processed (221/11322)
1989-08-10 processed (222/11322)
1989-08-11 processed (223/11322)
1989-08-12 processed (224/11322)
1989-08-13 processed (225/11322)
1989-08-14 processed (226/11322)
1989-08-15 processed (227/11322)
1989-08-16 processed (228/11322)
1989-08-17 processed (229/11322)
1989-08-18 processed (230/11322)
1989-08-19 processed (231/11322)
1989-08-20 processed (232/11322)
1989-08-21 processed (233/11322)
1989-08-22 processed (234/11322)
1989-08-23 processed (235/11322)
1989-08-24 processed (236/11322)
1989-08-25 processed (237/11322)
1989-08-26 processed (238/11322)
1989-08-27 processed (239/11322)
1989-08-28 processed (240/11322)
1989-08-29 processed (241/11322)
1989-08-30 processed (242/11322)
1989-08-31 processed (243/11322)
1989-09-01 processed (244/11322)
1989-09-02 processed (245/11322)
1989-09-03 processed (246/11322)
1989-09-04 processed (247/11322)
1989-09-05 processed (248/11322)
1989-09-06 processed (249/11322)
1989-09-07 processed (250/11322)
1989-09-08 processed (251/11322)
1989-09-09 processed (252/11322)
1989-09-10 processed (253/11322)
1989-09-11 processed (254/11322)
1989-09-12 processed (255/11322)
1989-09-13 processed (256/11322)
1989-09-14 processed (257/11322)
1989-09-15 processed (258/11322)
1989-09-16 processed (259/11322)
1989-09-17 processed (260/11322)
1989-09-18 processed (261/11322)
1989-09-19 processed (262/11322)
1989-09-20 processed (263/11322)
1989-09-21 processed (264/11322)
1989-09-22 processed (265/11322)
1989-09-23 processed (266/11322)
1989-09-24 processed (267/11322)
1989-09-25 processed (268/11322)
1989-09-26 processed (269/11322)
1989-09-27 processed (270/11322)
1989-09-28 processed (271/11322)
1989-09-29 processed (272/11322)
1989-09-30 processed (273/11322)
1989-10-01 processed (274/11322)
1989-10-02 processed (275/11322)
1989-10-03 processed (276/11322)
1989-10-04 processed (277/11322)
1989-10-05 processed (278/11322)
1989-10-06 processed (279/11322)
1989-10-07 processed (280/11322)
1989-10-08 processed (281/11322)
1989-10-09 processed (282/11322)
1989-10-10 processed (283/11322)
1989-10-11 processed (284/11322)
1989-10-12 processed (285/11322)
1989-10-13 processed (286/11322)
1989-10-14 processed (287/11322)
1989-10-15 processed (288/11322)
1989-10-16 processed (289/11322)
1989-10-17 processed (290/11322)
1989-10-18 processed (291/11322)
1989-10-19 processed (292/11322)
1989-10-20 processed (293/11322)
1989-10-21 processed (294/11322)
1989-10-22 processed (295/11322)
1989-10-23 processed (296/11322)
1989-10-24 processed (297/11322)
1989-10-25 processed (298/11322)
1989-10-26 processed (299/11322)
1989-10-27 processed (300/11322)
1989-10-28 processed (301/11322)
1989-10-29 processed (302/11322)
1989-10-30 processed (303/11322)
1989-10-31 processed (304/11322)
1989-11-01 processed (305/11322)
1989-11-02 processed (306/11322)
1989-11-03 processed (307/11322)
1989-11-04 processed (308/11322)
1989-11-05 processed (309/11322)
1989-11-06 processed (310/11322)
1989-11-07 processed (311/11322)
1989-11-08 processed (312/11322)
1989-11-09 processed (313/11322)
1989-11-10 processed (314/11322)
1989-11-11 processed (315/11322)
1989-11-12 processed (316/11322)
1989-11-13 processed (317/11322)
1989-11-14 processed (318/11322)
1989-11-15 processed (319/11322)
1989-11-16 processed (320/11322)
1989-11-17 processed (321/11322)
1989-11-18 processed (322/11322)
1989-11-19 processed (323/11322)
1989-11-20 processed (324/11322)
1989-11-21 processed (325/11322)
1989-11-22 processed (326/11322)
1989-11-23 processed (327/11322)
1989-11-24 processed (328/11322)
1989-11-25 processed (329/11322)
1989-11-26 processed (330/11322)
1989-11-27 processed (331/11322)
1989-11-28 processed (332/11322)
1989-11-29 processed (333/11322)
1989-11-30 processed (334/11322)
1989-12-01 processed (335/11322)
1989-12-02 processed (336/11322)
1989-12-03 processed (337/11322)
1989-12-04 processed (338/11322)
1989-12-05 processed (339/11322)
1989-12-06 processed (340/11322)
1989-12-07 processed (341/11322)
1989-12-08 processed (342/11322)
1989-12-09 processed (343/11322)
1989-12-10 processed (344/11322)
1989-12-11 processed (345/11322)
1989-12-12 processed (346/11322)
1989-12-13 processed (347/11322)
1989-12-14 processed (348/11322)
1989-12-15 processed (349/11322)
1989-12-16 processed (350/11322)
1989-12-17 processed (351/11322)
1989-12-18 processed (352/11322)
1989-12-19 processed (353/11322)
1989-12-20 processed (354/11322)
1989-12-21 processed (355/11322)
1989-12-22 processed (356/11322)
1989-12-23 processed (357/11322)
1989-12-24 processed (358/11322)
1989-12-25 processed (359/11322)
1989-12-26 processed (360/11322)
1989-12-27 processed (361/11322)
1989-12-28 processed (362/11322)
1989-12-29 processed (363/11322)
1989-12-30 processed (364/11322)
1989-12-31 processed (365/11322)
1990-01-01 processed (366/11322)
1990-01-02 processed (367/11322)
1990-01-03 processed (368/11322)
1990-01-04 processed (369/11322)
1990-01-05 processed (370/11322)
1990-01-06 processed (371/11322)
1990-01-07 processed (372/11322)
1990-01-08 processed (373/11322)
1990-01-09 processed (374/11322)
1990-01-10 processed (375/11322)
1990-01-11 processed (376/11322)
1990-01-12 processed (377/11322)
1990-01-13 processed (378/11322)
1990-01-14 processed (379/11322)
1990-01-15 processed (380/11322)
1990-01-16 processed (381/11322)
1990-01-17 processed (382/11322)
1990-01-18 processed (383/11322)
1990-01-19 processed (384/11322)
1990-01-20 processed (385/11322)
1990-01-21 processed (386/11322)
1990-01-22 processed (387/11322)
1990-01-23 processed (388/11322)
1990-01-24 processed (389/11322)
1990-01-25 processed (390/11322)
1990-01-26 processed (391/11322)
1990-01-27 processed (392/11322)
1990-01-28 processed (393/11322)
1990-01-29 processed (394/11322)
1990-01-30 processed (395/11322)
1990-01-31 processed (396/11322)
1990-02-01 processed (397/11322)
1990-02-02 processed (398/11322)
1990-02-03 processed (399/11322)
1990-02-04 processed (400/11322)
1990-02-05 processed (401/11322)
1990-02-06 processed (402/11322)
1990-02-07 processed (403/11322)
1990-02-08 processed (404/11322)
1990-02-09 processed (405/11322)
1990-02-10 processed (406/11322)
1990-02-11 processed (407/11322)
1990-02-12 processed (408/11322)
1990-02-13 processed (409/11322)
1990-02-14 processed (410/11322)
1990-02-15 processed (411/11322)
1990-02-16 processed (412/11322)
1990-02-17 processed (413/11322)
1990-02-18 processed (414/11322)
1990-02-19 processed (415/11322)
1990-02-20 processed (416/11322)
1990-02-21 processed (417/11322)
1990-02-22 processed (418/11322)
1990-02-23 processed (419/11322)
1990-02-24 processed (420/11322)
1990-02-25 processed (421/11322)
1990-02-26 processed (422/11322)
1990-02-27 processed (423/11322)
1990-02-28 processed (424/11322)
1990-03-01 processed (425/11322)
1990-03-02 processed (426/11322)
1990-03-03 processed (427/11322)
1990-03-04 processed (428/11322)
1990-03-05 processed (429/11322)
1990-03-06 processed (430/11322)
1990-03-07 processed (431/11322)
1990-03-08 processed (432/11322)
1990-03-09 processed (433/11322)
1990-03-10 processed (434/11322)
1990-03-11 processed (435/11322)
1990-03-12 processed (436/11322)
1990-03-13 processed (437/11322)
1990-03-14 processed (438/11322)
1990-03-15 processed (439/11322)
1990-03-16 processed (440/11322)
1990-03-17 processed (441/11322)
1990-03-18 processed (442/11322)
1990-03-19 processed (443/11322)
1990-03-20 processed (444/11322)
1990-03-21 processed (445/11322)
1990-03-22 processed (446/11322)
1990-03-23 processed (447/11322)
1990-03-24 processed (448/11322)
1990-03-25 processed (449/11322)
1990-03-26 processed (450/11322)
1990-03-27 processed (451/11322)
1990-03-28 processed (452/11322)
1990-03-29 processed (453/11322)
1990-03-30 processed (454/11322)
1990-03-31 processed (455/11322)
1990-04-01 processed (456/11322)
1990-04-02 processed (457/11322)
1990-04-03 processed (458/11322)
1990-04-04 processed (459/11322)
1990-04-05 processed (460/11322)
1990-04-06 processed (461/11322)
1990-04-07 processed (462/11322)
1990-04-08 processed (463/11322)
1990-04-09 processed (464/11322)
1990-04-10 processed (465/11322)
1990-04-11 processed (466/11322)
1990-04-12 processed (467/11322)
1990-04-13 processed (468/11322)
1990-04-14 processed (469/11322)
1990-04-15 processed (470/11322)
1990-04-16 processed (471/11322)
1990-04-17 processed (472/11322)
1990-04-18 processed (473/11322)
1990-04-19 processed (474/11322)
1990-04-20 processed (475/11322)
1990-04-21 processed (476/11322)
1990-04-22 processed (477/11322)
1990-04-23 processed (478/11322)
1990-04-24 processed (479/11322)
1990-04-25 processed (480/11322)
1990-04-26 processed (481/11322)
1990-04-27 processed (482/11322)
1990-04-28 processed (483/11322)
1990-04-29 processed (484/11322)
1990-04-30 processed (485/11322)
1990-05-01 processed (486/11322)
1990-05-02 processed (487/11322)
1990-05-03 processed (488/11322)
1990-05-04 processed (489/11322)
1990-05-05 processed (490/11322)
1990-05-06 processed (491/11322)
1990-05-07 processed (492/11322)
1990-05-08 processed (493/11322)
1990-05-09 processed (494/11322)
1990-05-10 processed (495/11322)
1990-05-11 processed (496/11322)
1990-05-12 processed (497/11322)
1990-05-13 processed (498/11322)
1990-05-14 processed (499/11322)
1990-05-15 processed (500/11322)
1990-05-16 processed (501/11322)
1990-05-17 processed (502/11322)
1990-05-18 processed (503/11322)
1990-05-19 processed (504/11322)
1990-05-20 processed (505/11322)
1990-05-21 processed (506/11322)
1990-05-22 processed (507/11322)
1990-05-23 processed (508/11322)
1990-05-24 processed (509/11322)
1990-05-25 processed (510/11322)
1990-05-26 processed (511/11322)
1990-05-27 processed (512/11322)
1990-05-28 processed (513/11322)
1990-05-29 processed (514/11322)
1990-05-30 processed (515/11322)
1990-05-31 processed (516/11322)
1990-06-01 processed (517/11322)
1990-06-02 processed (518/11322)
1990-06-03 processed (519/11322)
1990-06-04 processed (520/11322)
1990-06-05 processed (521/11322)
1990-06-06 processed (522/11322)
1990-06-07 processed (523/11322)
1990-06-08 processed (524/11322)
1990-06-09 processed (525/11322)
1990-06-10 processed (526/11322)
1990-06-11 processed (527/11322)
1990-06-12 processed (528/11322)
1990-06-13 processed (529/11322)
1990-06-14 processed (530/11322)
1990-06-15 processed (531/11322)
1990-06-16 processed (532/11322)
1990-06-17 processed (533/11322)
1990-06-18 processed (534/11322)
1990-06-19 processed (535/11322)
1990-06-20 processed (536/11322)
1990-06-21 processed (537/11322)
1990-06-22 processed (538/11322)
1990-06-23 processed (539/11322)
1990-06-24 processed (540/11322)
1990-06-25 processed (541/11322)
1990-06-26 processed (542/11322)
1990-06-27 processed (543/11322)
1990-06-28 processed (544/11322)
1990-06-29 processed (545/11322)
1990-06-30 processed (546/11322)
1990-07-01 processed (547/11322)
1990-07-02 processed (548/11322)
1990-07-03 processed (549/11322)
1990-07-04 processed (550/11322)
1990-07-05 processed (551/11322)
1990-07-06 processed (552/11322)
1990-07-07 processed (553/11322)
1990-07-08 processed (554/11322)
1990-07-09 processed (555/11322)
1990-07-10 processed (556/11322)
1990-07-11 processed (557/11322)
1990-07-12 processed (558/11322)
1990-07-13 processed (559/11322)
1990-07-14 processed (560/11322)
1990-07-15 processed (561/11322)
1990-07-16 processed (562/11322)
1990-07-17 processed (563/11322)
1990-07-18 processed (564/11322)
1990-07-19 processed (565/11322)
1990-07-20 processed (566/11322)
1990-07-21 processed (567/11322)
1990-07-22 processed (568/11322)
1990-07-23 processed (569/11322)
1990-07-24 processed (570/11322)
1990-07-25 processed (571/11322)
1990-07-26 processed (572/11322)
1990-07-27 processed (573/11322)
1990-07-28 processed (574/11322)
1990-07-29 processed (575/11322)
1990-07-30 processed (576/11322)
1990-07-31 processed (577/11322)
1990-08-01 processed (578/11322)
1990-08-02 processed (579/11322)
1990-08-03 processed (580/11322)
1990-08-04 processed (581/11322)
1990-08-05 processed (582/11322)
1990-08-06 processed (583/11322)
1990-08-07 processed (584/11322)
1990-08-08 processed (585/11322)
1990-08-09 processed (586/11322)
1990-08-10 processed (587/11322)
1990-08-11 processed (588/11322)
1990-08-12 processed (589/11322)
1990-08-13 processed (590/11322)
1990-08-14 processed (591/11322)
1990-08-15 processed (592/11322)
1990-08-16 processed (593/11322)
1990-08-17 processed (594/11322)
1990-08-18 processed (595/11322)
1990-08-19 processed (596/11322)
1990-08-20 processed (597/11322)
1990-08-21 processed (598/11322)
1990-08-22 processed (599/11322)
1990-08-23 processed (600/11322)
1990-08-24 processed (601/11322)
1990-08-25 processed (602/11322)
1990-08-26 processed (603/11322)
1990-08-27 processed (604/11322)
1990-08-28 processed (605/11322)
1990-08-29 processed (606/11322)
1990-08-30 processed (607/11322)
1990-08-31 processed (608/11322)
1990-09-01 processed (609/11322)

In [14]:
# Collect per-basin lists
basin_series = {gauge: [] for gauge in gauges}
dates = []

for date, values in all_results:
    dates.append(date)
    for gauge, val in values.items():
        basin_series[gauge].append(val)

dates = pd.to_datetime(dates)

# Save one CSV per basin
for gauge, values in basin_series.items():
    ts = pd.Series(values, index=dates, name="precipitation").sort_index()
    out_path = output_dir / f"{gauge}_precip.csv"
    ts.to_csv(out_path)
    print(f"Saved: {out_path}")

Saved: precip_timeseries_mswep_weighted_2/camels_01411300_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_01466500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_01487000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_01638480_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_01644000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_01666500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_01667500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_01669000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_01669520_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02027000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02038850_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02046000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02053200_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02053800_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02055100_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02064000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02065500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02081500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02082950_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02092500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02108000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02118500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02125000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02140991_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02143040_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02193340_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02202600_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02212600_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02215100_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02216180_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02221525_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02231000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02246000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02296500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02297310_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02298123_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02298608_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02299950_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02300700_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02342933_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02349900_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02350900_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02361000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02363000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02371500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02372250_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02374500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02381600_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02395120_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02415000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02427250_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02450250_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02464360_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02465493_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02469800_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02472000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02472500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02479155_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_02479560_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_03170000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_03281500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_03285000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_03439000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_03460000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_03498500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_03574500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_03604000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_05593575_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_05595730_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_06917000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_06918460_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_06919500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_06921070_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_06921200_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07057500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07060710_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07066000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07145700_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07184000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07195800_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07197000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07261000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07263295_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07291000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07299670_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07315200_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07335700_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07340300_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07346045_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07359610_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07362100_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_07375000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08013000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08014500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08023080_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08050800_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08066200_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08066300_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08070000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08070200_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08082700_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08086212_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08086290_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08101000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08104900_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08150800_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08158700_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08158810_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08164300_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08164600_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08165300_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08171300_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08175000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08176900_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08178880_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08189500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08190500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08195000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08198500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08200000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_08202700_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_09447800_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_09505800_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_10259000_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_11451100_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_12073500_precip.csv
Saved: precip_timeseries_mswep_weighted_2/camels_14362250_precip.csv